export const SHOW_PRODUCT='SHOW_PRODUCT'
export const SINGLE_PRODUCT='SINGLE_PRODUCT'
export const SEARCH_PRODUCT='SEARCH_PRODUCT'
export const LETEST_PRODUCT='LETEST_PRODUCT'


export const ADD_CART='ADD_CART'
export const CLEAR_CART='CLEAR_CART'
export const INCREMENT='INCREMENT'
export const DECREMENT='DECREMENT'
export const REMOVE_ITEM='REMOVE_ITEM'
export const ADD_TOTAL='ADD_TOTAL'
export const INCREMENT_ITEM='INCREMENT_ITEM'
export const DECREMENT_ITEM='DECREMENT_ITEM'



export const SUCCESS_UPLOAD='SUCCES_UPLOAD'
export const FAIL_UPLOAD='FAIL_UPLOAD'
export const SET_ERROR='SET_ERROR'
export const CLEAR_ERROR='CLEAR_ERROR'
export const SET_SUCCESS='SET_SUCCESS'
export const CLEAR_SUCCESS='CLEAR_SUCCESS'



export const ADD_CATEGORIES ='ADD_CATEGORIES'
export const GET_CATEGORIES ='GET_CATEGORIES'
export const DELETE_CATEGORIES ='DELETE_CATEGORIES'


export const SUCCES_REGISTER='SUCCES_REGISTER'
export const SUCCES_LOGIN='SUCCES_LOGIN'
export const LOG_OUT='LOG_OUT'
export const SET_ADMIN='SET_ADMIN'
export const SET_MESSAHE ='SET_MESSAHE'
export const CLEAR_MESSAGE='CLEAR_MESSAGE'



export const ADD_CONTACT = 'ADD_CONTACT'
export const ERROR_CONTACT = 'ERROR_CONTACT'

export const SET_USER = 'USER'


export const MAKE_PAYMENT = 'MAKE_PAYMENT'




   
   




