export const GET_PRODUCT='SHOW_PRODUCT'
export const SINGLE_PRODUCT='SINGLE_PRODUCT'
export const ADD_PRODUCT='ADD_PRODUCT'

export const UPDATE_PRODUCT ='UPDATE_PRODUCT'

// global
export const EDIT_FORM ='EDIT_FORM'
export const CLEAR_EDITFORM ='CLEAR_EDITFORM'
export const SET_ERROR='SET_ERROR'
export const CLEAR_SUCCESS='CLEAR_SUCCESS'
export const CLEAR_ERROR='CLEAR_ERROR'


export const GET_CUSTOMER='GET_CUSTOMER'
export const GET_SINGLE_CUSTOMER='GET_SINGLE_CUSTOMER'
export const ADD_CUSTOMER='ADD_CUSTOMER'
export const UPDATE_CUSTOMER='UPDATE_CUSTOMER'


export const GET_INVOICE='GET_INVOICE'
export const GET_SINGLE_INVOICE='GET_SINGLE_INVOICE'
export const ADD_INVOICE='ADD_INVOICE'
export const UPDATE_INVOICE='UPDATE_INVOICE'
export const DELETE_INVOICE='DELETE_INVOICE'




export const ADD_CART='ADD_CART'
export const CLEAR_CART='CLEAR_CART'
export const INCREMENT='INCREMENT'
export const DECREMENT='DECREMENT'
export const REMOVE_ITEM='REMOVE_ITEM'
export const ADD_TOTAL='ADD_TOTAL'
export const INCREMENT_ITEM='INCREMENT_ITEM'
export const DECREMENT_ITEM='DECREMENT_ITEM'



export const SUCCESS_UPLOAD='SUCCES_UPLOAD'
export const FAIL_UPLOAD='FAIL_UPLOAD'


export const SUCCES_REGISTER='SUCCES_REGISTER'
export const SUCCES_LOGIN='SUCCES_LOGIN'
export const LOG_OUT='LOG_OUT'
export const SET_ADMIN='SET_ADMIN'
export const SET_MESSAHE ='SET_MESSAHE'
export const CLEAR_MESSAGE='CLEAR_MESSAGE'


export const SET_USER = 'USER'





   
   




